attach(needdata)
Global_reactive_power<-as.numeric(as.character(Global_reactive_power))
png("plot4.png")
par(mfrow = c(2,2))
plot(datetime,Global_active_power,type = "l",xlab= "",ylab = "Global Active Power(kilowatts)")
plot(datetime,Voltage,type = "l",xlab= "datetime",ylab = "Voltage")
plot(datetime,Sub_metering_1,col = "black",type = "l",xlab = "",ylab = "Energy sub metering")
lines(datetime,Sub_metering_2,col = "red",type = "l")
lines(datetime,Sub_metering_3,col = "blue",type = "l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col = c("black","red","blue"))
plot(datetime, Global_reactive_power,type = "l")
dev.off()